Feature/add lonbok and exception
gaydukov/SoftensySpringBoot pull request #2
Opened 2021-09-07 14:25 UTC by gaydukov

2021-09-07 17:07 UTC, shelsoftensy requested changes

2021-09-07 17:07 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/controller/PatientControllerTest.java
>      void givenPatient_whenDeletePatient_thenStatus204() throws Exception {
camelCase only

2021-09-07 17:07 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/controller/PatientControllerTest.java
>      void givenPatients_whenGetPatients_thenStatus200andPatientsReturned() throws Exception {
camelCase only

2021-09-07 17:07 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/service/serviceImpl/DoctorServiceImplTest.java
>      void givenDoctors_whenGetAllDoctors_thenReturnAllDoctors() {
camelCase only

2021-09-07 17:07 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/service/serviceImpl/DoctorServiceImplTest.java
>      @DisplayName("delete doctor")
displayName for tests should display understandable test name for a person who did not see your code and functionality!

2021-09-07 17:07 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/service/serviceImpl/PatientServiceImplTest.java
>      void givenPatients_whenGetAllPatients_thenReturnAllPatients() {
camelCase

2021-09-08 06:28 UTC, gaydukov commented on pom.xml
> +        <relativePath/> <!-- lookup parent from repository -->
indicates the path to the parent pom.xml In this case, this tag is optional

2021-09-09 08:45 UTC, shelsoftensy requested changes

2021-09-09 08:45 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/handlerException/RestResponseEntityExceptionHandler.java
> +    protected ResponseEntity<Object> handleConflict(ResponseStatusException ex, WebRequest request) {
variable names

2021-09-09 08:45 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/entity/Doctor.java
>  @Table
do we need this annotation?

2021-09-09 08:45 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/entity/Patient.java
>  @Table
do we need it?

2021-09-09 08:45 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/controller/DoctorControllerTest.java
> +    @DisplayName("get all doctors returned doctors end status")
end ?

2021-09-09 08:45 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/controller/PatientControllerTest.java
>      @DisplayName("get patient by id returned doctor end status")
end?

2021-09-09 08:45 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/controller/PatientControllerTest.java
>      @DisplayName("save patient returned doctor end status")
end?

2021-09-09 12:27 UTC, shelsoftensy approved these changes

2021-09-09 12:32 UTC, merged