Feature/security
gaydukov/SoftensySpringBoot pull request #4
Opened 2021-09-29 07:07 UTC by gaydukov

2021-09-30 08:42 UTC, shelsoftensy requested changes

2021-09-30 08:42 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/configuration/SecurityConfig.java
> +        return new BCryptPasswordEncoder(12);
why here is 12, what default value is?

2021-09-30 08:42 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/configuration/SecurityConfig.java
> +                .httpBasic();
httpBasic, why do you use it here?

2021-09-30 08:42 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/dto/UserSecurityDetails.java
> +    }
do you need all this boilerplate code?

2021-09-30 08:42 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/entity/DoctorSecurity.java
> +public class DoctorSecurity extends UserSecurity {
if your app will have more entity types, you will add  more entitySecurity classes?

2021-09-30 08:42 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/mapper/UserSecurityMapper.java
> +                userSecurity.getRole().getAuthorities());
soup in constructor values? what is it?

2021-09-30 09:38 UTC, gaydukov commented on src/main/java/com/softensy/SoftensySpringBoot/configuration/SecurityConfig.java
> +        return new BCryptPasswordEncoder(12);
default value is 10

2021-10-01 10:04 UTC, shelsoftensy requested changes

2021-10-01 10:04 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/dto/UserSecurityDetails.java
> +    private final boolean isEnabled;
yagni?

2021-10-01 10:04 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/service/serviceImpl/UserDetailsServiceImpl.java
> +    private final AppointmentRepository appointmentRepository;
appointmentRepo in userDetails service???

2021-10-01 10:04 UTC, shelsoftensy commented on src/main/java/com/softensy/SoftensySpringBoot/service/serviceImpl/UserDetailsServiceImpl.java
> +        if (user.getAccountType() != AccountType.DOCTOR) {
constant value should be at the first place

2021-10-01 10:04 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/TestDataGenerator.java
> +        return new User("user", "user", true, true, true, true,
emm

2021-10-01 10:04 UTC, shelsoftensy commented on src/test/java/com/softensy/SoftensySpringBoot/controller/AppointmentControllerTest.java
> +    void testGetAppointmentToDoctorByDoctorIdWithAnotherAuthenticatedReturnStatus403() throws Exception {
AppointmentToDoctor?
english?

2021-10-29 11:33 UTC, merged